// <auto-generated />
using System;
using FinalProject_Group1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject_Group1.Migrations
{
    [DbContext(typeof(TeamInfoContext))]
    [Migration("FavoriteFood_Migration")]
    partial class FavoriteFoodsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject_Group1.Models.FavoriteFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("favBreakfast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favLunch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favDinner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("favDessert")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            favBreakfast = "Biscuits and Gravy",
                            favLunch = "Tacos, any kind!",
                            favDinner = "Steak and Potatoes",
                            favDessert = "Cheesecake"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
